#ifndef WMIDATA_H
#define WMIDATA_H

#include <NtAPI.h>

#ifndef _WMI_CHANGER_PROBLEM_DEVICE_ERROR
#define _WMI_CHANGER_PROBLEM_DEVICE_ERROR
typedef struct _WMI_CHANGER_PROBLEM_DEVICE_ERROR {
  ULONG ChangerProblemType;
} WMI_CHANGER_PROBLEM_DEVICE_ERROR, *PWMI_CHANGER_PROBLEM_DEVICE_ERROR;
#endif


#endif